### ISSUE TITLE
文字列の描写方法の模索

### ISSUE THREAD

**Issue by tobynet** [arigato-java/RealJavaButton#3]
## サマリー

ジャバボ表面に文字列を入れる方法について、コスパの高い方法を模索したい。
見栄えよく、低コスト（「お金」と「労力」を減らす)を実現できないか。

## 試した方法の一覧

|                 | 手間 |再利用性|仕上り| 参考リンク |
|-----------------|:----:|:-----:|:----:|-----------|
|ステンシル        |  ◯  |  ◯   |  ×    | |
|マスキングシート   |  ×   | △    |  ◯    | |
|2色成型              | (未評価) | (未評価) | (未評価) | |

## 参考情報

* ステンシル
  * Pros:
    * 再現性は、3Dプリンタに依存
    * 再利用しやすい
  * Cons:
    * 塗装の出来はわるい(画像は後述)
      * 対象物と密着させにくく、塗料がはみ出る
    * 出力と調整の繰り返しが何度か必要。
  * 工程例:
    1. CADでデータを作成
    1. 3Dプリンタにて型を出力
    1. ナイフで型を調整
    1. 対象に貼り付け、塗料を塗る

* マスキングシート
  * Pros:
    * 塗装の出来はわるくない(画像は後述)
  * Cons:
    * 「無料ジャバのダウンロード」の切り抜きに、一時間程度の時間と集中を要する。
    * 再利用しにくい(2,3回が限度か)
    * 出力と調整の繰り返しが何度か必要。
  * 工程例:
    1. Illustlator でデータ作成
    1. インクジェットプリンタを使い、マスキングシートに印字
    1. デザインナイフでシートを切り抜く
    1. 対象にシートを貼り付け、塗料を塗る

* デュアル3Dプリンタによる二色成型: 
  * (未評価)

## 参考画像

* ステンシル(?)での実装例
  1. ![dfnzyhluaaat3yx](https://user-images.githubusercontent.com/20859/28749682-db5fe5e4-750a-11e7-83f5-6353fc1ffb6d.jpg)
  1. ![dfrkstexsamsfis](https://user-images.githubusercontent.com/20859/28749672-589d28d8-750a-11e7-8b38-e8584546348d.jpg)
  1. ![dfqetn1voaanykr](https://user-images.githubusercontent.com/20859/28749676-73ec4182-750a-11e7-83fb-e0dfc8d40cc4.jpg)
* マスキングシートでの実装例
  1. ![dfxhsrguwaah8yk](https://user-images.githubusercontent.com/20859/28749687-fb123bee-750a-11e7-8216-34d308622be9.jpg)
  1. ![dfxj3o2uaaehgcp](https://user-images.githubusercontent.com/20859/28749686-fb0f2102-750a-11e7-86f2-a3cceb8abee0.jpg)
  1. ![df2sb9hu0aafwjv](https://user-images.githubusercontent.com/20859/28749685-fb0f32a0-750a-11e7-97c8-b61556ca7aee.jpg)

* TODO: 二色成型

## 他

* 他によい案はないか
* 改善方法はないか

**Comment by tomari** [comment]
キーボードでは、２色成形とよばれる方法が使われることがあります。
現在の3D プリンタのワークフローや精度に乗るかは不明ですが、再現性という面では期待が持てそうです。
http://www.yamashita-denki.co.jp/product/plastics/dm/dm02.html

**Comment by tobynet** [comment]
ありがとうございます、いい案ですね。

環境さえ用意できれば、再現性の面で大きいのがよいですね。
塗装を各自でやるのは、たいへんですので。。。

* **前提:** 塗装なし
* **データ:** 2色用の3Dデータを用意
* **3Dプリンタ:** デュアルで出力が可能なもの
　* **素材(フィラメント):** 赤白を用意

幸いうちはデュアルの機種なので、赤白のフィラメントを用意できれば試すことができます。

設計が必要なのと、ワークフローが変わるため、今回のプロトタイプ以降に試してみたいです。

**Comment by tomari** [comment]
その後ジャバ社の事務所でブレストをやっていました。その中で、インクジェット用の透明なステッカーシートを用いて文字を貼ってしまうというアイデアが出て、これは一考に値するかと思います。

**Comment by tobynet** [comment]
シールいいですね。

貼る表面を滑らかにしさえすれば、貼って終わりにできそうです。

**Comment by tobynet** [comment]
現行の家庭用インクジェットプリンタは白色を出力できないため、
（原作に忠実に再現するならば）白いステッカーなどで代用する必要があることが判明いたしました。

**Comment by tobynet** [comment]
パーツ分離による簡易化の方向[1] を検討中です。

[1] デュアルなプリンタでなくとも、それぞれ出力し、組み合わせればそれなりに見える方向

**Comment by tobynet** [comment]
途中経過です。
赤、白、別々に出力して、組み合わせたものです。

合成後

![javabutton-v2-00_dichg2kuiaaij33](https://user-images.githubusercontent.com/20859/29868166-e2345064-8db8-11e7-91b7-d2176408d6b7.jpg)

ラベル(の図)

![2017-08-29_javabutton-label00](https://user-images.githubusercontent.com/20859/29868292-5b47a58c-8db9-11e7-8186-79f390087870.png)


フタのみ

![javabutton-v2-00_0_diaabskuqaaf1h1](https://user-images.githubusercontent.com/20859/29868206-054786ca-8db9-11e7-995f-03715fb96f62.jpg)

**Comment by tomari** [comment]
最高です。これだと、押しすぎて文字の塗装が剥がれてしまうことがないわけで、大幅な改善になっていると思います。

**Comment by tobynet** [comment]
v2.x 系をアップしました。
https://github.com/arigato-java/RealJavaButton/tree/v2.x

v2.x 系には、改良後のものもあるのですが、githubにはアップしてません。周辺デザイナさんのウケが良くなかったもので。(実は、改良後のものの方が、組立しやすかったり、より文字が浮き出て見えたりはします)

## 以下、(アップされてない)改良後のもの:

* Fusion360の最新版へのリンク: http://a360.co/2l34Xsz
* 画像: 
![image](https://user-images.githubusercontent.com/20859/34330009-91354b40-e958-11e7-8a56-e72f8df7377c.png)

**Comment by tobynet** [comment]
イシュータイトルの目的はかなったので、いったん close します。
