### ISSUE TITLE
推奨出力環境の明示

### ISSUE THREAD

**Issue by tomari** [arigato-java/RealJavaButton#5]
以下情報をリドミに明示してほしい

* プリンタ名称、リビジョン等
* 樹脂タイプ
* ほか出力設定
* ソフトウェア環境

**Comment by tobynet** [comment]
了解です。ジャバ連の侵攻が開始されるまでには、用意をいたします。

**Comment by tobynet** [comment]
部品リスト、回路図以外を記載しました。 

書きなぐったので読みずらいです。 整える必要ありか。

**Comment by tomari** [comment]
上フタと下ケースのToolpath VIsualizationのエビデンスが逆になってませんか？
ラフトの状況からの推定です。

**Comment by tobynet** [comment]
Fix it . ( https://github.com/arigato-java/RealJavaButton/compare/1ca8b36...38f2cba  )

Thanks @tomari

**Comment by tobynet** [comment]
問題なければ、一旦クローズします
