### ISSUE TITLE
TGS出展

### ISSUE THREAD

**Issue by tomari** [arigato-java/RealJavaButton#6]
新型ゲーム機「ジャバボタン」をTGSで発表する

**Comment by tobynet** [comment]
「TGS前にリークされた新型ジャバボタン」として以下の写真が出回っています。
当組としての対処が必要ではないでしょうか。 

![case-lid02_2017-aug-27_02-51-38am-000_customizedview3516394165](https://user-images.githubusercontent.com/20859/29867928-17794e60-8db8-11e7-9407-8907f690d74c.png)

**Comment by tomari** [comment]
概ね、中国向けローカライゼーションを外注した大連の会社からのリークですね。連絡して警告しておきます。

**Comment by tomari** [comment]
お疲れ様でした。

**Comment by tomari** [comment]
予定が合わなかった人のために、現地のジャバボタンブースの様子を添付します

![tgs2017javabutton](https://user-images.githubusercontent.com/1059211/31574212-c02440c2-b105-11e7-8aa5-b7d106bc8ff8.jpg)

**Comment by tobynet** [comment]
TGS発表どうでしたか。また聞かせてください。お疲れ様でした!
